/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum ActivityTypeDTO {

    LABORATORY = 'LABORATORY',

    COURSE = 'COURSE',

    PROJECT = 'PROJECT',

    SEMINAR = 'SEMINAR',

    SPECIAL_EVENT = 'SPECIAL_EVENT'
}

