/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthUserDTO } from './auth-user';


export interface AuthOkResponseDTO { 
    ok: boolean;
    user: AuthUserDTO;
}

