/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPublicDTO } from './user-public';


export interface AuthOkResponseDTO { 
    ok: boolean;
    user: UserPublicDTO;
}

