/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreferredThemeDTO } from './preferred-theme';
import { UserRoleDTO } from './user-role';
import { PreferredLanguageDTO } from './preferred-language';


export interface AuthUserDTO { 
    id: string;
    email: string;
    role: UserRoleDTO;
    firstName: string | null;
    familyName: string | null;
    preferredLanguage?: PreferredLanguageDTO | null;
    preferredTheme?: PreferredThemeDTO | null;
    facultyId: string | null;
    programId: string | null;
    programYearId: string | null;
    groupCohortId: string | null;
    semigroupCohortId?: string | null;
}



