/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthUserDTO { 
    id: string;
    email: string;
    role: AuthUserDTORoleEnum;
    firstName: string | null;
    familyName: string | null;
    preferredLanguage?: AuthUserDTOPreferredLanguageEnum | null;
    preferredTheme?: AuthUserDTOPreferredThemeEnum | null;
    facultyId: string | null;
    programId: string | null;
    programYearId: string | null;
    groupCohortId: string | null;
    semigroupCohortId?: string | null;
}
export enum AuthUserDTORoleEnum {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
};
export enum AuthUserDTOPreferredLanguageEnum {
    EN = 'en',
    RO = 'ro'
};
export enum AuthUserDTOPreferredThemeEnum {
    DARK = 'DARK',
    LIGHT = 'LIGHT'
};



