/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvailabilitySlotDTO { 
    date: string;
    roomId: string;
    startHour: number;
    endHour: number;
    capacity: number;
    reservedSpots: number;
    busySpots: number;
    freeSpots: number;
    subjectId?: string;
    activityId?: string;
    cohortIds?: Array<string>;
}

