/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvailabilityQueryDTO { 
    date: string;
    roomId?: string;
    cohortId?: string;
    subjectId?: string;
    startHour?: number;
    endHour?: number;
    minFreeSpots?: number;
    limit?: number;
}

