/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingStatusDTO } from './booking-status';


export interface BookingUpdateDTO { 
    activityId?: string;
    status?: BookingStatusDTO;
}



