/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceDTO } from './source';
import { BookingStatusDTO } from './booking-status';


export interface BookingResponseDTO { 
    id: string;
    activityId: string;
    userId: string;
    cohortId?: string | null;
    status: BookingStatusDTO;
    createdAt: string;
    updatedAt?: string | null;
    source?: SourceDTO | null;
}



