/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum BookingStatusDTO {

    CONFIRMED = 'CONFIRMED',

    WAITLISTED = 'WAITLISTED',

    CANCELLED = 'CANCELLED'
}

