/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuildingCardFloorDTO } from './building-card-floor';


export interface BuildingsCardResponseDTO { 
    id: string;
    name: string;
    address: string;
    specialEvent: boolean;
    floors: Array<BuildingCardFloorDTO>;
}

