/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CohortTypeDTO } from './cohort-type';


export interface CohortBaseDTO { 
    type: CohortTypeDTO;
    programYearId: string;
    name: string;
    parentGroupId?: string | null;
}



