/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventTypeDTO } from './event-type';


export interface EventResponseDTO { 
    type?: EventTypeDTO;
    name: string;
    date: string;
    startHour: number;
    buildingId: string;
    roomId: string;
    reservedSpots: number;
    id: string;
}



