/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum PreferredLanguageDTO {

    EN = 'en',

    RO = 'ro',

    HI = 'hi',

    ZH_CN = 'zh-CN',

    KO = 'ko'
}

