/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DegreeDTO } from './degree';


export interface ProgramUpdateDTO { 
    facultyId?: string;
    name?: string;
    degree?: DegreeDTO;
    active?: boolean;
}



