/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityTypeDTO } from './activity-type';


export interface RescheduleOptionDTO { 
    activityId: string;
    subjectId: string;
    activityType: ActivityTypeDTO;
    date: string;
    weekDay: string;
    startHour: number;
    endHour: number;
    capacity: number;
    reservedSpots: number;
    busySpots: number;
    freeSpots: number;
    cohortIds: Array<string>;
}



