/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RescheduleOptionDTO } from './reschedule-option';
import { RescheduleOptionsResponseCurrentBookingDTO } from './reschedule-options-response-current-booking';


export interface RescheduleOptionsResponseDTO { 
    currentBooking: RescheduleOptionsResponseCurrentBookingDTO;
    items: Array<RescheduleOptionDTO>;
    total: number;
}

