/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityTypeDTO } from './activity-type';


export interface RescheduleOptionsResponseCurrentBookingDTO { 
    id: string;
    activityId: string;
    subjectId: string | null;
    activityType: ActivityTypeDTO;
    programYearId: string | null;
    groupCohortId: string | null;
    semigroupCohortId: string | null;
    originalActivityId?: string | null;
    isRescheduled?: boolean | null;
    rescheduledAt?: string | null;
}



