/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubjectIdArrayDTO } from './subject-id-array';


export interface RoomUpdateDTO { 
    floorId?: string;
    name?: string;
    totalSpotsNumber?: number;
    unavailableSpots?: number;
    subjectList?: SubjectIdArrayDTO;
}

