/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum SourceTypeDTO {

    ROOM_TIMETABLE = 'ROOM_TIMETABLE',

    COHORT_TIMETABLE = 'COHORT_TIMETABLE',

    EVENT = 'EVENT'
}

