/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeekParityDTO } from './week-parity';
import { ActivityTypeDTO } from './activity-type';
import { WeekDayDTO } from './week-day';


export interface TimetableActivityResponseDTO { 
    roomId: string;
    subjectId: string;
    date: string;
    weekDay: WeekDayDTO;
    activityType: ActivityTypeDTO;
    cohortIds: Array<string>;
    startHour: number;
    endHour: number;
    weekParity: WeekParityDTO;
    capacity: number;
    reservedSpots: number;
    busySpots: number;
    freeSpots: number;
    id: string;
}



