/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeekParityDTO } from './week-parity';
import { ActivityTypeDTO } from './activity-type';
import { WeekDayDTO } from './week-day';


export interface TimetableActivityCardResponseDTO { 
    id: string;
    weekDay: WeekDayDTO;
    startHour: number;
    endHour: number;
    weekParity: WeekParityDTO;
    activityType: ActivityTypeDTO;
    roomName: string;
    subjectItemShortName: string;
}



