/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreferredThemeDTO } from './preferred-theme';
import { PreferredLanguageDTO } from './preferred-language';


export interface UserMePreferencesUpdateDTO { 
    preferredLanguage?: PreferredLanguageDTO | null;
    preferredTheme?: PreferredThemeDTO | null;
}



