/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserMeProfileUpdateDTO { 
    firstName: string;
    familyName: string;
    facultyId: string;
    programId: string;
    programYearId: string;
    groupCohortId: string;
    semigroupCohortId?: string | null;
}

