/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPublicDTO { 
    id: string;
    email: string;
    role: UserPublicDTORoleEnum;
}
export enum UserPublicDTORoleEnum {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
};



