/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum WeekDayDTO {

    MONDAY = 'MONDAY',

    TUESDAY = 'TUESDAY',

    WEDNESDAY = 'WEDNESDAY',

    THURSDAY = 'THURSDAY',

    FRIDAY = 'FRIDAY',

    SATURDAY = 'SATURDAY',

    SUNDAY = 'SUNDAY'
}

