/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvailabilityGet200ResponseItemsInnerDTO } from './availability-get200-response-items-inner';


export interface AvailabilityResponseDTO { 
    items: Array<AvailabilityGet200ResponseItemsInnerDTO>;
    total: number;
}

