/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookingsIdGet200ResponseSourceDTO { 
    type: BookingsIdGet200ResponseSourceDTOTypeEnum;
    id: string;
}
export enum BookingsIdGet200ResponseSourceDTOTypeEnum {
    ROOM_TIMETABLE = 'ROOM_TIMETABLE',
    COHORT_TIMETABLE = 'COHORT_TIMETABLE',
    EVENT = 'EVENT'
};



