/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingsIdGet200ResponseSourceDTO } from './bookings-id-get200-response-source';


export interface BookingsIdGet200ResponseDTO { 
    id: string;
    activityId: string;
    userId: string;
    cohortId?: string | null;
    status: BookingsIdGet200ResponseDTOStatusEnum;
    createdAt: string;
    updatedAt?: string | null;
    source?: BookingsIdGet200ResponseSourceDTO | null;
}
export enum BookingsIdGet200ResponseDTOStatusEnum {
    CONFIRMED = 'CONFIRMED',
    WAITLISTED = 'WAITLISTED',
    CANCELLED = 'CANCELLED'
};



