/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookingUpdateDTO { 
    activityId?: string;
    status?: BookingUpdateDTOStatusEnum;
}
export enum BookingUpdateDTOStatusEnum {
    CONFIRMED = 'CONFIRMED',
    WAITLISTED = 'WAITLISTED',
    CANCELLED = 'CANCELLED'
};



