/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingsIdGet200ResponseSourceDTO } from './bookings-id-get200-response-source';


export interface BookingCreateDTO { 
    activityId: string;
    userId: string;
    status?: BookingCreateDTOStatusEnum;
    cohortId?: string | null;
    source?: BookingsIdGet200ResponseSourceDTO | null;
}
export enum BookingCreateDTOStatusEnum {
    CONFIRMED = 'CONFIRMED',
    WAITLISTED = 'WAITLISTED',
    CANCELLED = 'CANCELLED'
};



