/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CohortUpdateDTO { 
    type?: CohortUpdateDTOTypeEnum;
    name?: string;
    parentGroupId?: string | null;
}
export enum CohortUpdateDTOTypeEnum {
    GROUP = 'GROUP',
    SEMIGROUP = 'SEMIGROUP'
};



