/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CohortResponseDTO { 
    id: string;
    type: CohortResponseDTOTypeEnum;
    programYearId: string;
    name: string;
    parentGroupId?: string | null;
}
export enum CohortResponseDTOTypeEnum {
    GROUP = 'GROUP',
    SEMIGROUP = 'SEMIGROUP'
};



