/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CohortsPostRequestDTO { 
    type: CohortsPostRequestDTOTypeEnum;
    programYearId: string;
    name: string;
    parentGroupId?: string | null;
}
export enum CohortsPostRequestDTOTypeEnum {
    GROUP = 'GROUP',
    SEMIGROUP = 'SEMIGROUP'
};



