/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProgramUpdateDTO { 
    name?: string;
    degree?: ProgramUpdateDTODegreeEnum;
    active?: boolean;
}
export enum ProgramUpdateDTODegreeEnum {
    LIC = 'lic',
    MASTER = 'master',
    DOCT = 'doct'
};



