/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProgramResponseDTO { 
    id: string;
    facultyId: string;
    name: string;
    degree: ProgramResponseDTODegreeEnum;
    active: boolean;
}
export enum ProgramResponseDTODegreeEnum {
    LIC = 'lic',
    MASTER = 'master',
    DOCT = 'doct'
};



