/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProgramsPostRequestDTO { 
    facultyId: string;
    name: string;
    degree: ProgramsPostRequestDTODegreeEnum;
    active: boolean;
}
export enum ProgramsPostRequestDTODegreeEnum {
    LIC = 'lic',
    MASTER = 'master',
    DOCT = 'doct'
};



