/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoomCreateDTO { 
    buildingId: string;
    floorId: string;
    name: string;
    totalSpotsNumber: number;
    unavailableSpots: number;
    subjectList?: Array<string>;
}

