/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceTypeDTO } from './source-type';


export interface SourceDTO { 
    type: SourceTypeDTO;
    id: string;
}



