/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimetableActivitiesPostRequestDTO { 
    roomId: string;
    subjectId: string;
    date: string;
    weekDay: TimetableActivitiesPostRequestDTOWeekDayEnum;
    activityType: TimetableActivitiesPostRequestDTOActivityTypeEnum;
    cohortIds: Array<string>;
    startHour: number;
    endHour: number;
    weekParity: TimetableActivitiesPostRequestDTOWeekParityEnum;
    capacity: number;
    reservedSpots: number;
    busySpots: number;
    freeSpots: number;
}
export enum TimetableActivitiesPostRequestDTOWeekDayEnum {
    MONDAY = 'MONDAY',
    TUESDAY = 'TUESDAY',
    WEDNESDAY = 'WEDNESDAY',
    THURSDAY = 'THURSDAY',
    FRIDAY = 'FRIDAY',
    SATURDAY = 'SATURDAY',
    SUNDAY = 'SUNDAY'
};
export enum TimetableActivitiesPostRequestDTOActivityTypeEnum {
    LABORATORY = 'LABORATORY',
    COURSE = 'COURSE',
    PROJECT = 'PROJECT',
    SEMINAR = 'SEMINAR',
    SPECIAL_EVENT = 'SPECIAL_EVENT'
};
export enum TimetableActivitiesPostRequestDTOWeekParityEnum {
    BOTH = 'BOTH',
    EVEN = 'EVEN',
    ODD = 'ODD'
};



