/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeekParityDTO } from './week-parity';
import { ActivityTypeDTO } from './activity-type';
import { WeekDayDTO } from './week-day';
import { CohortIdArrayDTO } from './cohort-id-array';


export interface TimetableActivityUpdateDTO { 
    roomId?: string;
    subjectId?: string;
    date?: string;
    weekDay?: WeekDayDTO;
    activityType?: ActivityTypeDTO;
    cohortIds?: CohortIdArrayDTO;
    startHour?: number;
    endHour?: number;
    weekParity?: WeekParityDTO;
    capacity?: number;
    reservedSpots?: number;
    busySpots?: number;
    freeSpots?: number;
}



