/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimetableActivitiesIdPatchRequestDTO { 
    roomId?: string;
    subjectId?: string;
    date?: string;
    weekDay?: TimetableActivitiesIdPatchRequestDTOWeekDayEnum;
    activityType?: TimetableActivitiesIdPatchRequestDTOActivityTypeEnum;
    cohortIds?: Array<string>;
    startHour?: number;
    endHour?: number;
    weekParity?: TimetableActivitiesIdPatchRequestDTOWeekParityEnum;
    capacity?: number;
    reservedSpots?: number;
    busySpots?: number;
    freeSpots?: number;
}
export enum TimetableActivitiesIdPatchRequestDTOWeekDayEnum {
    MONDAY = 'MONDAY',
    TUESDAY = 'TUESDAY',
    WEDNESDAY = 'WEDNESDAY',
    THURSDAY = 'THURSDAY',
    FRIDAY = 'FRIDAY',
    SATURDAY = 'SATURDAY',
    SUNDAY = 'SUNDAY'
};
export enum TimetableActivitiesIdPatchRequestDTOActivityTypeEnum {
    LABORATORY = 'LABORATORY',
    COURSE = 'COURSE',
    PROJECT = 'PROJECT',
    SEMINAR = 'SEMINAR',
    SPECIAL_EVENT = 'SPECIAL_EVENT'
};
export enum TimetableActivitiesIdPatchRequestDTOWeekParityEnum {
    BOTH = 'BOTH',
    EVEN = 'EVEN',
    ODD = 'ODD'
};



