/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsersIdGet200ResponseDTO { 
    id: string;
    email: string;
    firstName: string;
    familyName: string;
    role: UsersIdGet200ResponseDTORoleEnum;
    preferredLanguage?: UsersIdGet200ResponseDTOPreferredLanguageEnum | null;
    preferredTheme?: UsersIdGet200ResponseDTOPreferredThemeEnum | null;
    facultyId: string;
    programYearId: string;
    groupCohortId: string;
    semigroupCohortId?: string | null;
}
export enum UsersIdGet200ResponseDTORoleEnum {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
};
export enum UsersIdGet200ResponseDTOPreferredLanguageEnum {
    EN = 'en',
    RO = 'ro'
};
export enum UsersIdGet200ResponseDTOPreferredThemeEnum {
    DARK = 'DARK',
    LIGHT = 'LIGHT'
};



