/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUpdateDTO { 
    firstName?: string;
    familyName?: string;
    role?: UserUpdateDTORoleEnum;
    preferredLanguage?: UserUpdateDTOPreferredLanguageEnum | null;
    preferredTheme?: UserUpdateDTOPreferredThemeEnum | null;
    facultyId?: string;
    programYearId?: string;
    groupCohortId?: string;
    semigroupCohortId?: string | null;
}
export enum UserUpdateDTORoleEnum {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
};
export enum UserUpdateDTOPreferredLanguageEnum {
    EN = 'en',
    RO = 'ro'
};
export enum UserUpdateDTOPreferredThemeEnum {
    DARK = 'DARK',
    LIGHT = 'LIGHT'
};



