/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsersPostRequestDTO { 
    email: string;
    firstName: string;
    familyName: string;
    role: UsersPostRequestDTORoleEnum;
    preferredLanguage?: UsersPostRequestDTOPreferredLanguageEnum | null;
    preferredTheme?: UsersPostRequestDTOPreferredThemeEnum | null;
    facultyId: string;
    programYearId: string;
    groupCohortId: string;
    semigroupCohortId?: string | null;
}
export enum UsersPostRequestDTORoleEnum {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
};
export enum UsersPostRequestDTOPreferredLanguageEnum {
    EN = 'en',
    RO = 'ro'
};
export enum UsersPostRequestDTOPreferredThemeEnum {
    DARK = 'DARK',
    LIGHT = 'LIGHT'
};



