/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserResponseDTO { 
    id: string;
    email: string;
    firstName: string;
    familyName: string;
    role: UserResponseDTORoleEnum;
    preferredLanguage?: UserResponseDTOPreferredLanguageEnum | null;
    preferredTheme?: UserResponseDTOPreferredThemeEnum | null;
    facultyId: string;
    programYearId: string;
    groupCohortId: string;
    semigroupCohortId?: string | null;
}
export enum UserResponseDTORoleEnum {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
};
export enum UserResponseDTOPreferredLanguageEnum {
    EN = 'en',
    RO = 'ro'
};
export enum UserResponseDTOPreferredThemeEnum {
    DARK = 'DARK',
    LIGHT = 'LIGHT'
};



