/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsersIdPatchRequestDTO { 
    firstName?: string;
    familyName?: string;
    role?: UsersIdPatchRequestDTORoleEnum;
    preferredLanguage?: UsersIdPatchRequestDTOPreferredLanguageEnum | null;
    preferredTheme?: UsersIdPatchRequestDTOPreferredThemeEnum | null;
    facultyId?: string;
    programYearId?: string;
    groupCohortId?: string;
    semigroupCohortId?: string | null;
}
export enum UsersIdPatchRequestDTORoleEnum {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
};
export enum UsersIdPatchRequestDTOPreferredLanguageEnum {
    EN = 'en',
    RO = 'ro'
};
export enum UsersIdPatchRequestDTOPreferredThemeEnum {
    DARK = 'DARK',
    LIGHT = 'LIGHT'
};



