/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserCreateDTO { 
    email: string;
    firstName: string;
    familyName: string;
    role: UserCreateDTORoleEnum;
    preferredLanguage?: UserCreateDTOPreferredLanguageEnum | null;
    preferredTheme?: UserCreateDTOPreferredThemeEnum | null;
    facultyId: string;
    programYearId: string;
    groupCohortId: string;
    semigroupCohortId?: string | null;
}
export enum UserCreateDTORoleEnum {
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
};
export enum UserCreateDTOPreferredLanguageEnum {
    EN = 'en',
    RO = 'ro'
};
export enum UserCreateDTOPreferredThemeEnum {
    DARK = 'DARK',
    LIGHT = 'LIGHT'
};



