export * from './availability.service';
import { AvailabilityHttpService } from './availability.service';
export * from './bookings.service';
import { BookingsHttpService } from './bookings.service';
export * from './buildings.service';
import { BuildingsHttpService } from './buildings.service';
export * from './cohorts.service';
import { CohortsHttpService } from './cohorts.service';
export * from './faculties.service';
import { FacultiesHttpService } from './faculties.service';
export * from './floors.service';
import { FloorsHttpService } from './floors.service';
export * from './program-years.service';
import { ProgramYearsHttpService } from './program-years.service';
export * from './programs.service';
import { ProgramsHttpService } from './programs.service';
export * from './rooms.service';
import { RoomsHttpService } from './rooms.service';
export * from './subjects.service';
import { SubjectsHttpService } from './subjects.service';
export * from './timetable-activities.service';
import { TimetableActivitiesHttpService } from './timetable-activities.service';
export * from './users.service';
import { UsersHttpService } from './users.service';
export const APIS = [AvailabilityHttpService, BookingsHttpService, BuildingsHttpService, CohortsHttpService, FacultiesHttpService, FloorsHttpService, ProgramYearsHttpService, ProgramsHttpService, RoomsHttpService, SubjectsHttpService, TimetableActivitiesHttpService, UsersHttpService];
