/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { AvailabilityResponseDTO } from '../model/availability-response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface AvailabilityGetRequestParams {
    date: string;
    roomId?: string;
    cohortId?: string;
    subjectId?: string;
    startHour?: number;
    endHour?: number;
    minFreeSpots?: number;
    limit?: number;
}


@Injectable({
  providedIn: 'root'
})
export class AvailabilityHttpService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public availabilityGet(requestParameters: AvailabilityGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<AvailabilityResponseDTO>;
    public availabilityGet(requestParameters: AvailabilityGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<AvailabilityResponseDTO>>;
    public availabilityGet(requestParameters: AvailabilityGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<AvailabilityResponseDTO>>;
    public availabilityGet(requestParameters: AvailabilityGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const date = requestParameters?.date;
        if (date === null || date === undefined) {
            throw new Error('Required parameter date was null or undefined when calling availabilityGet.');
        }
        const roomId = requestParameters?.roomId;
        const cohortId = requestParameters?.cohortId;
        const subjectId = requestParameters?.subjectId;
        const startHour = requestParameters?.startHour;
        const endHour = requestParameters?.endHour;
        const minFreeSpots = requestParameters?.minFreeSpots;
        const limit = requestParameters?.limit;

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>date, 'date');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>roomId, 'roomId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>cohortId, 'cohortId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>subjectId, 'subjectId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startHour, 'startHour');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endHour, 'endHour');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>minFreeSpots, 'minFreeSpots');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>limit, 'limit');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/availability`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<AvailabilityResponseDTO>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
