/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AvailabilityGet200ResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AvailabilityHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param date 
     * @param roomId 
     * @param cohortId 
     * @param subjectId 
     * @param startHour 
     * @param endHour 
     * @param minFreeSpots 
     * @param limit 
     */
    availabilityGet(date: string, roomId?: string, cohortId?: string, subjectId?: string, startHour?: number, endHour?: number, minFreeSpots?: number, limit?: number, extraHttpRequestParams?: any): Observable<AvailabilityGet200ResponseDTO>;

}
