/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BookingsIdGet200ResponseDTO } from '../model/models';
import { BookingsIdPatchRequestDTO } from '../model/models';
import { BookingsPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BookingsHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    bookingsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    bookingsIdGet(id: string, extraHttpRequestParams?: any): Observable<BookingsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param bookingsIdPatchRequestDTO 
     */
    bookingsIdPatch(id: string, bookingsIdPatchRequestDTO?: BookingsIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<BookingsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param bookingsPostRequestDTO 
     */
    bookingsPost(bookingsPostRequestDTO?: BookingsPostRequestDTO, extraHttpRequestParams?: any): Observable<BookingsIdGet200ResponseDTO>;

}
