/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BuildingsIdGet200ResponseDTO } from '../model/models';
import { BuildingsIdPatchRequestDTO } from '../model/models';
import { BuildingsPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BuildingsHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    buildingsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    buildingsIdGet(id: string, extraHttpRequestParams?: any): Observable<BuildingsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param buildingsIdPatchRequestDTO 
     */
    buildingsIdPatch(id: string, buildingsIdPatchRequestDTO?: BuildingsIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<BuildingsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param buildingsPostRequestDTO 
     */
    buildingsPost(buildingsPostRequestDTO?: BuildingsPostRequestDTO, extraHttpRequestParams?: any): Observable<BuildingsIdGet200ResponseDTO>;

}
