/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CohortsIdGet200ResponseDTO } from '../model/models';
import { CohortsIdPatchRequestDTO } from '../model/models';
import { CohortsPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CohortsHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    cohortsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    cohortsIdGet(id: string, extraHttpRequestParams?: any): Observable<CohortsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param cohortsIdPatchRequestDTO 
     */
    cohortsIdPatch(id: string, cohortsIdPatchRequestDTO?: CohortsIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<CohortsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param cohortsPostRequestDTO 
     */
    cohortsPost(cohortsPostRequestDTO?: CohortsPostRequestDTO, extraHttpRequestParams?: any): Observable<CohortsIdGet200ResponseDTO>;

}
