/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FloorsIdGet200ResponseDTO } from '../model/models';
import { FloorsIdPatchRequestDTO } from '../model/models';
import { FloorsPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FloorsHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    floorsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    floorsIdGet(id: string, extraHttpRequestParams?: any): Observable<FloorsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param floorsIdPatchRequestDTO 
     */
    floorsIdPatch(id: string, floorsIdPatchRequestDTO?: FloorsIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<FloorsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param floorsPostRequestDTO 
     */
    floorsPost(floorsPostRequestDTO?: FloorsPostRequestDTO, extraHttpRequestParams?: any): Observable<FloorsIdGet200ResponseDTO>;

}
