/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProgramsIdGet200ResponseDTO } from '../model/models';
import { ProgramsIdPatchRequestDTO } from '../model/models';
import { ProgramsPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProgramsHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    programsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    programsIdGet(id: string, extraHttpRequestParams?: any): Observable<ProgramsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param programsIdPatchRequestDTO 
     */
    programsIdPatch(id: string, programsIdPatchRequestDTO?: ProgramsIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<ProgramsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param programsPostRequestDTO 
     */
    programsPost(programsPostRequestDTO?: ProgramsPostRequestDTO, extraHttpRequestParams?: any): Observable<ProgramsIdGet200ResponseDTO>;

}
