/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProgramYearsIdGet200ResponseDTO } from '../model/models';
import { ProgramYearsIdPatchRequestDTO } from '../model/models';
import { ProgramYearsPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProgramYearsHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    programYearsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    programYearsIdGet(id: string, extraHttpRequestParams?: any): Observable<ProgramYearsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param programYearsIdPatchRequestDTO 
     */
    programYearsIdPatch(id: string, programYearsIdPatchRequestDTO?: ProgramYearsIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<ProgramYearsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param programYearsPostRequestDTO 
     */
    programYearsPost(programYearsPostRequestDTO?: ProgramYearsPostRequestDTO, extraHttpRequestParams?: any): Observable<ProgramYearsIdGet200ResponseDTO>;

}
