/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RoomsIdGet200ResponseDTO } from '../model/models';
import { RoomsIdPatchRequestDTO } from '../model/models';
import { RoomsPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoomsHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    roomsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    roomsIdGet(id: string, extraHttpRequestParams?: any): Observable<RoomsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param roomsIdPatchRequestDTO 
     */
    roomsIdPatch(id: string, roomsIdPatchRequestDTO?: RoomsIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<RoomsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param roomsPostRequestDTO 
     */
    roomsPost(roomsPostRequestDTO?: RoomsPostRequestDTO, extraHttpRequestParams?: any): Observable<RoomsIdGet200ResponseDTO>;

}
