/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SubjectsIdGet200ResponseDTO } from '../model/models';
import { SubjectsIdPatchRequestDTO } from '../model/models';
import { SubjectsPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SubjectsHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    subjectsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    subjectsIdGet(id: string, extraHttpRequestParams?: any): Observable<SubjectsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param subjectsIdPatchRequestDTO 
     */
    subjectsIdPatch(id: string, subjectsIdPatchRequestDTO?: SubjectsIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<SubjectsIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param subjectsPostRequestDTO 
     */
    subjectsPost(subjectsPostRequestDTO?: SubjectsPostRequestDTO, extraHttpRequestParams?: any): Observable<SubjectsIdGet200ResponseDTO>;

}
