/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TimetableActivitiesIdGet200ResponseDTO } from '../model/models';
import { TimetableActivitiesIdPatchRequestDTO } from '../model/models';
import { TimetableActivitiesPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TimetableActivitiesHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    timetableActivitiesIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    timetableActivitiesIdGet(id: string, extraHttpRequestParams?: any): Observable<TimetableActivitiesIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param timetableActivitiesIdPatchRequestDTO 
     */
    timetableActivitiesIdPatch(id: string, timetableActivitiesIdPatchRequestDTO?: TimetableActivitiesIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<TimetableActivitiesIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param timetableActivitiesPostRequestDTO 
     */
    timetableActivitiesPost(timetableActivitiesPostRequestDTO?: TimetableActivitiesPostRequestDTO, extraHttpRequestParams?: any): Observable<TimetableActivitiesIdGet200ResponseDTO>;

}
