/**
 * FreeSpot API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UsersIdGet200ResponseDTO } from '../model/models';
import { UsersIdPatchRequestDTO } from '../model/models';
import { UsersPostRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersHttpServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    usersIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    usersIdGet(id: string, extraHttpRequestParams?: any): Observable<UsersIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param usersIdPatchRequestDTO 
     */
    usersIdPatch(id: string, usersIdPatchRequestDTO?: UsersIdPatchRequestDTO, extraHttpRequestParams?: any): Observable<UsersIdGet200ResponseDTO>;

    /**
     * 
     * 
     * @param usersPostRequestDTO 
     */
    usersPost(usersPostRequestDTO?: UsersPostRequestDTO, extraHttpRequestParams?: any): Observable<UsersIdGet200ResponseDTO>;

}
