export {
  AdminAcademicActivityType,
  AdminAcademicCohortType,
  AdminAcademicDegreeType,
  AdminAcademicWeekDay,
  AdminAcademicWeekParity,
  type AdminAcademicRoom,
  type AdminAcademicTimetableActivity,
  type AdminAcademicUser,
  type AdminCohort,
  type AdminFaculty,
  type AdminProgram,
  type AdminProgramYear,
  type AdminSubjectItem,
  type CreateAdminCohortCmd,
  type CreateAdminProgramCmd,
  type CreateAdminProgramYearCmd,
  type UpdateAdminAcademicUserCmd,
  type UpdateAdminFacultyCmd,
  type UpdateAdminProgramCmd,
  type UpdateAdminProgramYearCmd,
} from './lib/admin-academic-structure.models';
